# Generated by Django 4.0.5 on 2022-08-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_emails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
