# Generated by Django 4.0.5 on 2022-08-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_automation_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='EmailList1',
            new_name='EmailList',
        ),
        migrations.AlterField(
            model_name='automation',
            name='name',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='emails',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='base.tags'),
        ),
    ]
