# Generated by Django 4.0.5 on 2022-08-17 12:40

from django.db import migrations, models
import django_fsm
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_tags_rename_emaillist1_emaillist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='Condition',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='Condition_details',
            field=jsonfield.fields.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='automation',
            name='state',
            field=django_fsm.FSMField(choices=[('Running', 'Running'), ('Stopped', 'Stopped'), ('Not-published', 'Not-published')], default='Not-published', max_length=50, protected=True),
        ),
    ]
